version: "3.4"
services:

  prom:
    image: prom/prometheus:latest
    ports:
      - 81:9090
    volumes:
      - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml

  graf:
    image: grafana/grafana
    ports:
      - 80:3000
    volumes:
      - ./graf/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    depends_on:
      - prom

  animal-name-service:
    build: animal-name-service

  scientist-name-service:
    build: scientist-name-service

  name-generator-service:
    build: name-generator-service
    ports:
      - 83:8080

  jaeger:
    image: jaegertracing/all-in-one:1.17
    ports:
      - 82:16686
    depends_on:
      - prom
